### ISSUE TITLE
Error: Plugin "cordova-plugin-game" (1.0.114) failed to install.

### ISSUE THREAD

**Issue by elvisish** [cranberrygame/cordova-plugin-game#11]
I'm getting this error when I try to build with XDK. I've fixed the additions xml file and installed the plugin via github, why is it saying this?

**Comment by elvisish** [comment]
I've tried CLI 4.1.2 and 5.1.1 and both have the same fault.

**Comment by elvisish** [comment]
@cranberrygame what is causing this?

**Comment by cranberrygame** [comment]
Seems to build well now in xdk.
If not, reply.
Thanks
Sang Ki Kwon

**Comment by tox999** [comment]
Hello,
@cranberrygame I have the same problem with:
Error: Plugin "cordova-plugin-game" (1.0.116) failed to install.
when building with XDK I tried 4.1.2. and 5.1.1. CLI.
Do you think you can tell me how to fix it?

Tom

**Comment by cranberrygame** [comment]
@elvisish 
@tox999 

Still this build error?

Thanks
Sang Ki Kwon

**Comment by cranberrygame** [comment]
@elvisish 
@tox999 
Fixed this issue.
Thanks
Sang Ki Kwon
