### ISSUE TITLE
Update to Grandle?

### ISSUE THREAD

**Issue by mobilino** [cranberrygame/cordova-plugin-game#12]
Hi,

I use this plugin together with cordova-admob-pro on phonegap build. Since cordova-admob-pro updated to build with grandle and you both are using play-services my build fails now. 
"Error: more than one library with package name 'com.google.android.gms'"

It would be really cool if you could update to grandle too? I think all you need to do is to change in your config.xml your 
		\<dependency id="cordova-plugin-extras-google-play-services" /\>
		\<dependency id="cordova-plugin-extras-android-support-library-v4" /\>
to the corresponding \<framework\>-Tags. 

I feel that is the only option to enable builds with these two plugins.

/Christof

**Comment by mobilino** [comment]
ah, and I saw a similar plugin, cordova-plugin-play-games-services just wrote 

> Modified to include the new Google Play Services with com.google.android.gms:play-services and avoid some compiling errors. (Available also through npm, new Plugin Registry Format)

and they included the following into their plugin.xml:
```
        <framework src="com.google.android.gms:play-services-games:+" />
        <framework src="com.google.android.gms:play-services-plus:+" />
```
 Maybe this is also doing the trick here?

**Comment by cranberrygame** [comment]
@mobilino 
Fixed this issue.
Thank you very much!
Sang Ki Kwon

**Comment by mobilino** [comment]
That was quick, thanks!

Could you push the change to npm too? I am using phonegap build and get errors concerning the AppStateManager which you already eliminated in the version here.

**Comment by cranberrygame** [comment]
@mobilino 
Hi
Need to push this update to npm too next day.
Wait little more.
Thanks
Sang Ki Kwon

**Comment by mobilino** [comment]
OK!

/Christof

**Comment by cranberrygame** [comment]
@mobilino 
Pushed this update to npm.
Thanks
Sang Ki Kwon
