### ISSUE TITLE
Clear default account

### ISSUE THREAD

**Issue by FallenRiteMonk** [cranberrygame/cordova-plugin-game#4]
Hy,

would it be possible to get the possibility to clear the default account so that a different account can be signed in without having to clear app data?

**Comment by cranberrygame** [comment]
1.android

Setting - Account - Google - Logout with previous google account and login with other google account

2.ios

Setting - Game Center - Logout with previous ios account and login with other ios account

Thanks

**Comment by FallenRiteMonk** [comment]
What I ment by this is that if I have multiple Google accounts and want only the game to use a different one, i cant change this without going into google play games and logging out my account there from the game. In other games if i logout and then log back in I can specify again which account I want to use
