### ISSUE TITLE
Getting multiple playerscores bug

### ISSUE THREAD

**Issue by FallenRiteMonk** [cranberrygame/cordova-plugin-game#5]
If i try to get multiple player scores one after the other like:
```
window.game.getPlayerScore(leaderboardId-1, "tag-1");
window.game.getPlayerScore(leaderboardId-2, "tag-2");
```
and have a the succesfuntion as follows:
```
window.game.onGetPlayerScoreSucceeded = function(result) {
                var playerScore = result;
                console.log(window.game.onGetPlayerScoreSucceeded.tag);
                console.log('onGetPlayerScoreSucceeded: ' + playerScore);
            };
```
I receve the result of leaderboardId-1 with tag-2

**Comment by cranberrygame** [comment]
@FallenRiteMonk 

Sorry for late reply.
You can do like following.

window.game.getPlayerScore(leaderboardId-1, "tag-1");
window.game.getPlayerScore(leaderboardId-2, "tag-2");
and have a the succesfuntion as follows:

window.game.onGetPlayerScoreSucceeded = function(result) {
    var playerScore = result;
	console.log(window.game.tag);//do this!!!
	console.log('onGetPlayerScoreSucceeded: ' + playerScore);
};

Thanks
Sang Ki Kwon
