### ISSUE TITLE
I can't connect

### ISSUE THREAD

**Issue by sinmsinm** [cranberrygame/cordova-plugin-game#7]
Hi, I've been trying to use the plugin. I've followed the steps and after a setUp process fails on login. I got the following log trace
E/SignInIntentService(24350): Access Not Configured. The API (Google Play Game Services API) is not enabled for your project. Please use the Google Developers Console to update your configuration.
E/SignInIntentService(24350): com.google.android.gms.games.server.error.GamesException
E/SignInIntentService(24350): 	at com.google.android.gms.games.server.GamesServer.getResponseBlocking(GamesServer.java:164)
E/SignInIntentService(24350): 	at com.google.android.gms.games.broker.PlayerAgent.getPlayerFromNetwork(PlayerAgent.java:1744)
E/SignInIntentService(24350): 	at com.google.android.gms.games.broker.PlayerAgent.fetchPlayer(PlayerAgent.java:625)
E/SignInIntentService(24350): 	at com.google.android.gms.games.broker.DataBroker.loadSelf(DataBroker.java:837)
E/SignInIntentService(24350): 	at com.google.android.gms.games.service.PlayGamesSignInIntentService$LoadSelfOperation.executeInternal(PlayGamesSignInIntentService.java:402)
E/SignInIntentService(24350): 	at com.google.android.gms.games.service.PlayGamesSignInIntentService$BaseOperation.execute(PlayGamesSignInIntentService.java:51)
E/SignInIntentService(24350): 	at com.google.android.gms.games.service.PlayGamesSignInIntentService$OperationAdapter.execute(PlayGamesSignInIntentService.java:487)
E/SignInIntentService(24350): 	at com.google.android.gms.chimera.BaseAsyncOperationService$OperationTask.run(BaseAsyncOperationService.java:179)
E/SignInIntentService(24350): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/SignInIntentService(24350): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/SignInIntentService(24350): 	at java.lang.Thread.run(Thread.java:841)
E/LoadSelfFragment( 2507): Unable to sign in - application does not have a registered client ID
W/SignInActivity( 2507): onSignInFailed()...

Any idea what's going on?

**Comment by sinmsinm** [comment]
The API was not active. Sorry. Not an issue

**Comment by cranberrygame** [comment]
Ok
Thanks
