### ISSUE TITLE
Dependency warnings

### ISSUE THREAD

**Issue by AdrianNostromo** [cranberrygame/cordova-plugin-game#8]
When I add the plugin to a cordova project I get some warnings, here is the console output:
$ cordova plugin add cordova-plugin-game --variable APP_ID="000_SOME_NUMBERS_000"
Fetching plugin "cordova-plugin-game" via npm
Installing "cordova-plugin-game" for android
Fetching plugin "com.google.playservices@21.0.0" via npm
WARNING: com.google.playservices has been renamed to cordova-plugin-googleplayservices. You may not be getting the latest version! We suggest you `cordova plugin rm com.google.playservices` and `cordova plugin add cordova-plugin-googleplayservices`.
Fetching plugin "com.google.playservices@21.0.0" via cordova plugins registry
Installing "com.google.playservices" for android
Fetching plugin "android.support.v4@1.0.0" via npm
WARNING: android.support.v4 has been renamed to cordova-plugin-android-support-v4. You may not be getting the latest version! We suggest you `cordova plugin rm android.support.v4` and `cordova plugin add cordova-plugin-android-support-v4`.
Fetching plugin "android.support.v4@1.0.0" via cordova plugins registry
Installing "android.support.v4" for android

**Comment by cranberrygame** [comment]
@AdrianNostromo 

Removed this warning.
Thanks
