### ISSUE TITLE
Intel XDK Failed to build.

### ISSUE THREAD

**Issue by condolent** [cranberrygame/cordova-plugin-game#9]
My Android project in Intel XDK failed to build because of the plugin:
**Error: Plugin "https://github.com/cranberrygame/cordova-plugin-game --variable APP_ID='840521360412'" failed to install.**

Help pls

**Comment by cranberrygame** [comment]
@condolent 
If you are construct2 user, then make xdk project like this: https://dl.dropboxusercontent.com/u/186681453/How_to_cordova/How_to_install_c2_native_plugins_in_xdk/index.html

Thanks
